version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:  echo "Hello, Aijan!"
      - run: ls
      - run: yarn react-scripts test
      - run: echo "Tests passed!"

