version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.10.3
    steps:
      - add_ssh_keys:
            fingerprints:
              - "91:3e:b4:c4:4e:f5:d7:ad:e6:e9:9d:c3:54:3d:68:0c"
      - checkout
      - run: yarn install
      - run: yarn test
      - run: echo "Tests passed!"
      - run: yarn run deploy
      - run: echo "The app is deployed!"


